export const wheelLogoImagesData = [
  {
    picture:
      "https://raw.githubusercontent.com/alexek1987/fitnesspoker_assets/master/logos/gym_logo.png",
  },
  {
    picture:
      "https://raw.githubusercontent.com/alexek1987/fitnesspoker_assets/master/logos/functional_logo.png",
  },
  {
    picture:
      "https://raw.githubusercontent.com/alexek1987/jagharaldrig_assets/master/logos/pestellerkolera_xxx_logo.png",
  },
  {
    picture:
      "https://raw.githubusercontent.com/alexek1987/fitnesspoker_assets/master/logos/yoga_logo.png",
  },
  {
    picture:
      "https://raw.githubusercontent.com/alexek1987/fitnesspoker_assets/master/logos/body_logo.png",
  },
  {
    picture:
      "https://raw.githubusercontent.com/alexek1987/jagharaldrig_assets/master/logos/jagharaldrig_xxx_logo.png",
  },
  {
    picture:
      "https://raw.githubusercontent.com/alexek1987/fitnesspoker_assets/master/logos/gym_logo.png",
  },
  {
    picture:
      "https://raw.githubusercontent.com/alexek1987/fitnesspoker_assets/master/logos/functional_logo.png",
  },
  {
    picture:
      "https://raw.githubusercontent.com/alexek1987/jagharaldrig_assets/master/logos/pestellerkolera_xxx_logo.png",
  },
  {
    picture:
      "https://raw.githubusercontent.com/alexek1987/fitnesspoker_assets/master/logos/yoga_logo.png",
  },
  {
    picture:
      "https://raw.githubusercontent.com/alexek1987/fitnesspoker_assets/master/logos/body_logo.png",
  },
  {
    picture:
      "https://raw.githubusercontent.com/alexek1987/jagharaldrig_assets/master/logos/jagharaldrig_xxx_logo.png",
  },
];
